name: ytdl-sub
services:
  app:
    container_name: ytdl-sub
    image: ghcr.io/jmbannon/ytdl-sub:latest
    restart: unless-stopped
    environment:
      DOCKER_MODS: linuxserver/mods:universal-cron
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: DOCKER_MODS
          description:
            en_us: for enabling the cron job
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports: []
    volumes:
      - type: bind
        source: /DATA/AppData/ytdl-sub/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /media
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    command: []
    cpu_shares: 10
    deploy:
      resources:
        limits:
          memory: 256M
    hostname: ytdl-sub
    labels:
      icon: https://static-00.iconduck.com/assets.00/youtube-dl-icon-512x512-0n8x1tr8.png
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  title:
    en_us: YouTube_DL
  description:
    en_us: 'Visit project homepage: https://github.com/jmbannon/ytdl-sub'
  tagline:
    en_us: A tool to monitor YT channels and automatically download the content with matadata for Emby/Plex as TV Shows.
  project_url: https://github.com/jmbannon/ytdl-sub
  developer:LinuxServer.io
  author: the4tress
  category: LinuxServer.io
  hostname: https://github.com
  index: /jmbannon/ytdl-sub
  port_map: ""
  is_uncontrolled: false
  icon: https://static-00.iconduck.com/assets.00/youtube-dl-icon-512x512-0n8x1tr8.png
  thumbnail: https://static-00.iconduck.com/assets.00/youtube-dl-icon-512x512-0n8x1tr8.png
  scheme: https
  store_app_id: infallible_kaity
  tips:
    custom: Use a file editor to edit the files in the /config folder.

