name: linuxserver-ytdl-sub
services:
  app:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    restart: unless-stopped
    environment:
      DOCKER_MODS: 'linuxserver/mods:universal-cron'
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: DOCKER_MODS
          description:
            en_us: for enabling the cron job
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    volumes:
      - type: bind
        source: /DATA/AppData/ytdl-sub/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /media
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Visit project homepage
  tagline:
    en_us: A tool to monitor YT channels
  developer: Hashed.Life
  author: the4tress
  icon: 'https://static-00.iconduck.com/assets.00/youtube-dl-icon-512x512-0n8x1tr8.png'
  thumbnail: 'https://static-00.iconduck.com/assets.00/youtube-dl-icon-512x512-0n8x1tr8.png'
  title:
    en_us: YTDL-sub
  category: Hashed.Life

